[package]
name = "winit-cursor-hide-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow   = "1.0"
pollster = "0.3"
wgpu     = "0.16"
winit    = { git = "https://github.com/rust-windowing/winit", branch = "master", version = "0.28.6" }
